<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>TCM_Launcher</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<NoWarn>$(NoWarn);NU1903</NoWarn>
	<Version>0.0.4</Version>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	<AssemblyTitle></AssemblyTitle>
	<ApplicationIcon>Assets\TCM.ico</ApplicationIcon>
	<AssemblyName>$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\def_prof_img.png" />
    <None Remove="Assets\mc_img.png" />
    <None Remove="Assets\TCM.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\def_prof_img.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\mc_img.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\TCM.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
    <PackageReference Include="CmlLib.Core.Commons" Version="4.0.0" />
    <PackageReference Include="CmlLib.Core.Installer.Forge" Version="1.1.1" />
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" NoWarn="NU1701" />
    <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="MineStat" Version="3.1.2" />
    <PackageReference Include="Onova" Version="2.6.13" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TCM Launcher Backend\TCML Class library\TCML Class library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="Assets\LoadImg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </SplashScreen>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="View\UserControls\Misc\CustomTooltip.xaml.cs">
      <Generator>Compile</Generator>
    </Compile>
  </ItemGroup>

</Project>
