// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCM_Launcher.Core.DBContext;

#nullable disable

namespace TCM_Launcher.Migrations
{
    [DbContext(typeof(LauncherDBContext))]
    [Migration("20260705090820_GameProfileAddFileName")]
    partial class GameProfileAddFileName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TCM_Launcher.Model.DB.GameProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForgeVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MCVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
