// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCM_Launcher.Core.DBContext;

#nullable disable

namespace TCM_Launcher.Migrations
{
    [DbContext(typeof(LauncherDBContext))]
    [Migration("20260727094701_UpdateGameProfileAddPinned")]
    partial class UpdateGameProfileAddPinned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TCM_Launcher.Model.DB.AppMetaData", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppMetaData");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.GameProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForgeVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Installed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LastPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MCVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Pinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameProfiles");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.ProfileSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JVMArgs")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ram")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameProfileId");

                    b.ToTable("ProfileSettings");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BindedProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MCVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BindedProfileId");

                    b.ToTable("SavedServers");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.Versions.ForgeVersion", b =>
                {
                    b.Property<string>("VersionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MCVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.HasKey("VersionName");

                    b.ToTable("ForgeVersions");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.Versions.VanillaVersion", b =>
                {
                    b.Property<string>("VersionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VersionName");

                    b.ToTable("VanillaVersions");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.ProfileSettings", b =>
                {
                    b.HasOne("TCM_Launcher.Model.DB.GameProfile", "GameProfile")
                        .WithMany()
                        .HasForeignKey("GameProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProfile");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.Server", b =>
                {
                    b.HasOne("TCM_Launcher.Model.DB.GameProfile", "BindedProfile")
                        .WithMany()
                        .HasForeignKey("BindedProfileId");

                    b.Navigation("BindedProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
