// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCM_Launcher.Core.DBContext;

#nullable disable

namespace TCM_Launcher.Migrations
{
    [DbContext(typeof(LauncherDBContext))]
    [Migration("20260706150435_UpdateGameProfilesAddLastPlayed")]
    partial class UpdateGameProfilesAddLastPlayed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TCM_Launcher.Model.DB.GameProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForgeVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Installed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LastPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MCVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameProfiles");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.Versions.ForgeVersion", b =>
                {
                    b.Property<string>("VersionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MCVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.HasKey("VersionName");

                    b.ToTable("ForgeVersions");
                });

            modelBuilder.Entity("TCM_Launcher.Model.DB.Versions.VanillaVersion", b =>
                {
                    b.Property<string>("VersionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VersionName");

                    b.ToTable("VanillaVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
